all:
	make -C US1
	make -C US3
	make -C V400
	make -C V401
	make -C V407
	make -C V500
	make -C V503
	make -C V504
	make -C V601
	make -C V606
	make -C V703
	make -C V704

clean:
	make -C US1  clean
	make -C US3  clean
	make -C V400 clean
	make -C V401 clean
	make -C V407 clean
	make -C V500 clean
	make -C V503 clean
	make -C V504 clean
	make -C V601 clean
	make -C V606 clean
	make -C V703 clean
	make -C V704 clean

.PHONY: all clean