all:
	make -C V101
	make -C V106
	make -C V203
	make -C V206
	make -C V302
	make -C V308
	make -C V353
	make -C V355

clean:
	make -C V101 clean
	make -C V106 clean
	make -C V203 clean
	make -C V206 clean
	make -C V302 clean
	make -C V308 clean
	make -C V353 clean
	make -C V355 clean

.PHONY: all clean